#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : dtc
Version  : 1.4.6
Release  : 12
URL      : https://www.kernel.org/pub/software/utils/dtc/dtc-1.4.6.tar.gz
Source0  : https://www.kernel.org/pub/software/utils/dtc/dtc-1.4.6.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: dtc-bin
Requires: dtc-lib
BuildRequires : bison
BuildRequires : flex
BuildRequires : pbr
BuildRequires : pip

BuildRequires : python3-dev
BuildRequires : setuptools
Patch1: prefix.patch
Patch2: 0001-Disable-Werror.patch

%description
The source tree contains the Device Tree Compiler (dtc) toolchain for
working with device tree source and binary files and also libfdt, a
utility library for reading and manipulating the binary format.

%package bin
Summary: bin components for the dtc package.
Group: Binaries

%description bin
bin components for the dtc package.


%package dev
Summary: dev components for the dtc package.
Group: Development
Requires: dtc-lib
Requires: dtc-bin
Provides: dtc-devel

%description dev
dev components for the dtc package.


%package lib
Summary: lib components for the dtc package.
Group: Libraries

%description lib
lib components for the dtc package.


%prep
%setup -q -n dtc-1.4.6
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1523572203
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1523572203
rm -rf %{buildroot}
%make_install NO_PYTHON=1

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/convert-dtsv0
/usr/bin/dtc
/usr/bin/dtdiff
/usr/bin/fdtdump
/usr/bin/fdtget
/usr/bin/fdtoverlay
/usr/bin/fdtput

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib/libfdt-1.4.6.so
/usr/lib/libfdt.so

%files lib
%defattr(-,root,root,-)
/usr/lib/libfdt.so.1
