#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : dtc
Version  : 1.4.1
Release  : 7
URL      : https://www.kernel.org/pub/software/utils/dtc/dtc-1.4.1.tar.gz
Source0  : https://www.kernel.org/pub/software/utils/dtc/dtc-1.4.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: dtc-bin
Requires: dtc-lib
BuildRequires : bison
BuildRequires : flex
Patch1: prefix.patch

%description
The source tree contains the Device Tree Compiler (dtc) toolchain for
working with device tree source and binary files and also libfdt, a
utility library for reading and manipulating the binary format.

%package bin
Summary: bin components for the dtc package.
Group: Binaries

%description bin
bin components for the dtc package.


%package dev
Summary: dev components for the dtc package.
Group: Development
Requires: dtc-lib
Requires: dtc-bin

%description dev
dev components for the dtc package.


%package lib
Summary: lib components for the dtc package.
Group: Libraries

%description lib
lib components for the dtc package.


%prep
%setup -q -n dtc-1.4.1
%patch1 -p1

%build
make V=1 %{?_smp_mflags}

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/convert-dtsv0
/usr/bin/dtc
/usr/bin/dtdiff
/usr/bin/fdtdump
/usr/bin/fdtget
/usr/bin/fdtput

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib/*.so

%files lib
%defattr(-,root,root,-)
/usr/lib/*.so.*
